set nocompatible

filetype on
filetype plugin on
filetype indent on








"""""""""""""""VUNDLE CONFIGS START""""""""""""""""""""""""""""



"filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'


Plugin 'scrooloose/nerdtree.git'
Plugin 'scrooloose/nerdcommenter'

Plugin 'altercation/vim-colors-solarized'

Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"

Bundle "honza/vim-snippets"

Plugin 'pangloss/vim-javascript'

" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'

" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line



"""""""""""""""VUNDLE CONFIGS END""""""""""""""""""""""""""""




set autoread

set autoindent
set smartindent
set smarttab

set nowrap
set tabstop=4
set softtabstop=4
set linespace=1
set shiftwidth=4
set expandtab
set ruler
set cursorline
"set paste "для режима "вставки"

set showmatch
set hlsearch
set incsearch
set noignorecase

set lz
set listchars=tab:\ \ ,trail:~
set list

set wildmenu
set laststatus=2
set statusline=%<%f\ [%Y%R%W]%1*%{(&modified)?'\ [+]\ ':''}%*%=%c%V,%l\ %P\ [%n]

set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,cp1251,cp866,koi8-r

set nobackup
set noswapfile

set foldcolumn=1
set foldmethod=syntax
set foldnestmax=10
set nofoldenable

set scrolljump=5
set scrolloff=3

set synmaxcol=1000

"call pathogen#runtime_append_all_bundles()

set background=light
colorscheme solarized

let g:airline_theme='light'

set t_Co=256
syntax off "чтобы не было глюков при правке собраных js файлов в 10к+ строк

set linebreak
set pastetoggle=<F3>

set backspace=indent,eol,start

" Загрузка предыдущей сессии
set viminfo='10,\"100,:20,%,n~/.viminfo

map QQ :q <Cr>
map <silent> <C-t> <ESC> :tabedit .<Cr>
map <silent> ] <ESC> :tabnext <Cr>
map <silent> [ <ESC> :tabNext <Cr>

"защита от очептяк
command W w
command Q q
command WQ wq
command Wq wq


" шорткаты для комманд
command SO syntax on
command SF syntax off


"для того, чтобы в русской раскладке работали служебные клавиши
map й q
map ц w
map у e
map к r
map е t
map н y
map г u
map ш i
map щ o
map з p
map х [
map ъ ]
map ф a
map ы s
map в d
map а f
map п g
map р h
map о j
map л k
map д l
map я z
map ч x
map с c
map м v
map и b
map т n
map ь m
map б ,
map ю .



"Plugins configs
let NERDTreeShowHidden=1


""""""" Мои горячие клавиши:

map <F2> :w <CR>
map <F4> :q <CR>
map <F5> <ESC><C-W><C-W>

imap <F2> <ESC>:w <CR> i "хоткеи для режима ввода
imap <F4> <ESC>:q <CR>

map ,so :syntax on<CR>
map ,sf :syntax off<CR>

" Открыть дерево проекта
"map ,o :25vs<CR>:E<CR>iii
map ,o :NERDTreeToggle<CR>

" TODO:
" запилить переключение между табами на Ctrl+стрелки (стандартно - в режиме команды gt и gT)

" Меняем курсор для режима ввода http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

map > <C-W>>
map < <C-W><

